config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('contact/', include('contact.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contact/urls.py
from django.urls import path
from .views import contact_view

urlpatterns = [
    path('', contact_view, name='contact'),
    #path('subscribe/', subcribe_view, name='subs'),
]

posts/urls.py
from django.urls import path
from .views import hom_view, fash_view,travel_view,about_view,single_view
app_name='posts'    # {% url 'app_name:urlname' %}

urlpatterns = [
    path('', hom_view, name = 'home'),
    path('single/<slug:slug>/', single_view, name='single'),
    path('fashion/', fash_view, name='fashion'),
    path('travel/', travel_view, name='travel'),
    path('about/', about_view, name='about'),
]

contact/models.py
from django.db import models


class GetInTouch(models.Model):
    name = models.CharField(max_length=221)
    email = models.EmailField()
    subject = models.CharField(max_length=221)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Subscribe(models.Model):
    email = models.EmailField()

    def __str__(self):
        return self.email

posts/models.py
from django.db import models

TYPE = (
    (0, 'FASHION'),
    (1, 'TRAVEL'),
)


class Category(models.Model):
    title = models.CharField(max_length=221)

    def __str__(self):
        return self.title

class Tag(models.Model):
    tag = models.CharField(max_length=221)

    def __str__(self):
        return self.tag

# get_<field_name>_display
def post_image_path(instance, filename):
    return 'posts/%s/%s' % (instance.get_type_display(), filename)


class Post(models.Model):
    title = models.CharField(max_length=221)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    type = models.IntegerField(choices=TYPE, null=True)
    slug = models.SlugField(null=True)
    image = models.ImageField(upload_to=post_image_path)
    written_by = models.ImageField(upload_to=post_image_path , null=True)
    name = models.CharField(max_length=200 , null=True)
    content = models.TextField()
    written = models.TextField(null=True)
    tags = models.ManyToManyField(Tag, blank=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateField(null=True)

    def __str__(self):
        return self.title


class Comment(models.Model):
    article = models.ForeignKey(Post, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=221)
    avatar = models.ImageField(upload_to='comments', null=True)
    website = models.URLField(null=True, blank=True)
    email = models.EmailField()
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

contact/forms.py
from dataclasses import fields
from pyexpat import model
from django import forms
from .models import GetInTouch, Subscribe

class Contactform(forms.ModelForm):
    class Meta:
        model = GetInTouch
        fields = ['name', 'email', 'subject', 'message']

    def __init__(self, *args, **kwargs):
        super(Contactform, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field_name    
    
class SubscribeForm(forms.ModelForm):
    class Meta:
        model = Subscribe
        fields=['email']
    

posts/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        #fields = ('name', 'avatar', 'avatar', 'email', 'website', 'message')
        fields = '__all__'
        exclude = ['article']

    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field_name

            
    


contact/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
from .forms import Contactform
# Create your views here.
def contact_view(request):
    form = Contactform(request.POST or None)
    if form.is_valid():
        form.save() 
        messages.success(request, 'successfully send your message')
        return redirect('#contact/')
    context = {
        'form': form
    }
    return render(request, 'contact/contact.html', context)

posts/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .models import Comment, Category, Tag, Post
from contact.models import Subscribe
from .forms import CommentForm
def hom_view(request):
    posts = Post.objects.order_by('-id')
    cates = request.GET.get('cates')
    last_2_articles = Post.objects.order_by('-id')[:3]
    categories = Category.objects.all()
    tags = Tag.objects.all()    
    tag = request.GET.get('tag')
    email = request.GET.get('email')
    if email:
        Subscribe.objects.create(email=email)
    if tag:
        posts = posts.filter(tags__tag__exact=tag)
    if cates:
        posts = posts.filter(category__title__exact=cates)
    context = {'object_list' : posts,'categories': categories,'tags': tags, 'last_2_articles': last_2_articles,}

    return render(request, 'posts/index.html', context)

def single_view(request, slug):
    form = CommentForm()
    article = get_object_or_404(Post, slug=slug)
    last_2_articles = Post.objects.order_by('-id')[:3]
    categories = Category.objects.all()
    tags = Tag.objects.all()
    comments = Comment.objects.filter(article__slug=slug)

    if request.method == 'POST':
        form = CommentForm(request.POST, request.FILES)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.article = article
            comment.save()
            return redirect(f'/single/{article.slug}#comments')
    context = {
        #'object_list' : posts,
        'object': article,
        'last_2_articles': last_2_articles,
        'categories': categories,
        'tags': tags,
        'comments': comments,
        'form':form
    }

    return render(request, 'posts/single.html', context)

def fash_view(request):
    posts = Post.objects.order_by('-id')
    query = request.GET.get('query')
    if query:
        posts = posts.filter(title__icontains=query)
    context = {
        'object_list' : posts,
        'searchs':query,
    }

    return render(request, 'posts/fashion.html', context)

def travel_view(request):
    posts = Post.objects.order_by('-id')
    categories = Category.objects.all()
    last_2_articles = Post.objects.order_by('-id')[:3]
    tags = Tag.objects.all()
    context = {'object_list' : posts,'categories': categories,'tags': tags, 'last_2_articles': last_2_articles,}

    return render(request, 'posts/travel.html', context)

def about_view(request):
    posts = Post.objects.order_by('-id')

    context = {'object_list' : posts}

    return render(request, 'posts/about.html', context)




templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Andera</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i&amp;display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Abril+Fatface&amp;display=swap" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <script nonce="5295d087-18c0-461e-929e-2c3e8ee45a80">(function (w, d) {
        !function (a, e, t, r) {
            a.zarazData = a.zarazData || {}, a.zarazData.executed = [], a.zaraz = {deferred: []}, a.zaraz.q = [], a.zaraz._f = function (e) {
                return function () {
                    var t = Array.prototype.slice.call(arguments);
                    a.zaraz.q.push({m: e, a: t})
                }
            };
            for (const e of ["track", "set", "ecommerce", "debug"]) a.zaraz[e] = a.zaraz._f(e);
            a.addEventListener("DOMContentLoaded", (() => {
                var t = e.getElementsByTagName(r)[0], z = e.createElement(r),
                    n = e.getElementsByTagName("title")[0];
                for (a.zarazData.c = e.cookie, n && (a.zarazData.t = e.getElementsByTagName("title")[0].text), a.zarazData.w = a.screen.width, a.zarazData.h = a.screen.height, a.zarazData.j = a.innerHeight, a.zarazData.e = a.innerWidth, a.zarazData.l = a.location.href, a.zarazData.r = e.referrer, a.zarazData.k = a.screen.colorDepth, a.zarazData.n = e.characterSet, a.zarazData.o = (new Date).getTimezoneOffset(), a.zarazData.q = []; a.zaraz.q.length;) {
                    const e = a.zaraz.q.shift();
                    a.zarazData.q.push(e)
                }
                z.defer = !0, z.referrerPolicy = "origin", z.src = "../../cdn-cgi/zaraz/sd0d9.js?z=" + btoa(encodeURIComponent(JSON.stringify(a.zarazData))), t.parentNode.insertBefore(z, t)
            }))
        }(w, d, 0, "script");
    })(window, document);</script>

</head>
<body>

<div id="colorlib-page">
    <a href="#" class="js-colorlib-nav-toggle colorlib-nav-toggle"><i></i></a>
    {% include 'sidebar.html' %}
    {% block content %}

    {% endblock %}
   </div>


    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/jquery-migrate-3.0.1.min.js%2bpopper.min.js%2bbootstrap.min.js.pagespeed.jc.ufA-InWYhU.js' %}"></script>
    <script>eval(mod_pagespeed_j9z0BOW3Xo);</script>
    <script>eval(mod_pagespeed_Sv59xs6XfY);</script>
    <script>eval(mod_pagespeed_6hivBMilT4);</script>
    <script src="{% static 'js/jquery.easing.1.3.js%2bjquery.waypoints.min.js%2bjquery.stellar.min.js%2bowl.carousel.min.js.pagespeed.jc.7Uf8nwPPt3.js' %}"></script>
    <script>eval(mod_pagespeed_a9in6ca9LP);</script>
    <script>eval(mod_pagespeed_E5Rl_eUdra);</script>
    <script>eval(mod_pagespeed_J7fR9gg3IV);</script>
    <script>eval(mod_pagespeed_JGC9XV$UWo);</script>
    <script src="{% static 'js/jquery.magnific-popup.min.js%2baos.js%2bjquery.animateNumber.min.js%2bscrollax.min.js%2bgoogle-map.js%2bmain.js.pagespeed.jc.noK85cOv9x.js' %}"></script>
    <script>eval(mod_pagespeed_9FDixMCPbL);</script>
    <script>eval(mod_pagespeed_cWDp1F0K9O);</script>
    <script>eval(mod_pagespeed_tBed9FYmsP);</script>
    <script>eval(mod_pagespeed_xipmmYMCNr);</script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&amp;sensor=false"></script>
    <script>eval(mod_pagespeed_YuUFcjXVeT);</script>
    <script>eval(mod_pagespeed_6pY$MsZg3C);</script>

    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"></script>
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }

        gtag('js', new Date());

        gtag('config', 'UA-23581568-13');
    </script>
    <script defer
            src="https://static.cloudflareinsights.com/beacon.min.js/v652eace1692a40cfa3763df669d7439c1639079717194"
            integrity="sha512-Gi7xpJR8tSkrpF7aordPZQlW2DLtzUlZcumS8dMQjwDHEnw9I7ZLyiOj/6tZStRBGtGgN6ceN6cMH8z7etPGlw=="
            data-cf-beacon='{"rayId":"6fccc2540930fe3c","token":"cd0b4b3a733644fc843ef0b185f98241","version":"2021.12.0","si":100}'
            crossorigin="anonymous"></script>
</body>
</html>

templates/pagination.html
<div class="row">
    <div class="col text-center text-md-left">
        <div class="block-27">
            <ul>
                <li><a href="#">&lt;</a></li>
                <li class="active"><span>1</span></li>
                <li><a href="#">2</a></li>
                <li><a href="#">3</a></li>
                <li><a href="#">4</a></li>
                <li><a href="#">5</a></li>
                <li><a href="#">&gt;</a></li>
            </ul>
        </div>
    </div>
</div>

templates/posts/about.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

        <div id="colorlib-main">
            <section class="ftco-about img ftco-section ftco-no-pt ftco-no-pb" id="about-section">
                <div class="container-fluid px-0">
                    <div class="row d-flex">
                        <div class="col-md-6 d-flex">
                            <div class="img d-flex align-self-stretch align-items-center js-fullheight"
                                 style="background-image:url({% static 'images/photo_2022-04-20_09-29-26.jpg' %})">
                            </div>
                        </div>
                        <div class="col-md-6 d-flex align-items-center">
                            <div class="text px-4 pt-5 pt-md-0 px-md-4 pr-md-5 ftco-animate">
                                <h2 class="mb-4">I'm <span>Bexzod Abdumannonov</span> a Software Engineer &amp; Explorer</h2>
                                <p>A small river named Duden flows by their place and supplies it with the necessary
                                    regelialia. It is a paradisematic country, in which roasted parts of sentences fly
                                    into your mouth. It is a paradisematic country, in which roasted parts of sentences
                                    fly into your mouth.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>


{% endblock %}

templates/posts/fashion.html
{% extends 'base.html' %}
{% block content %}
    <div id="colorlib-main">
        <section class="ftco-section">
            <div class="container">
                <div class="row px-md-4">
                    <div class="col-md-12">
                        {% for object in object_list %}
                        <div class="blog-entry ftco-animate d-md-flex">
                            <a href="{% url 'posts:single' object.slug%}" class="img img-2"
                               style="background-image:url({{ object.image.url }})"></a>
                            <div class="text text-2 pl-md-4">
                                <h3 class="mb-2"><a href="{% url 'posts:single' object.slug %}">{{ object.title }}</a></h3>
                                <div class="meta-wrap">
                                    <p class="meta">
                                        <span><i class="icon-calendar mr-2"></i>{{ object.created_at|date:'M d, Y' }}</span>
                                        <span><a href="/?cates={{ object.category }}"><i class="icon-folder-o mr-2"></i>{{ object.category }}</a></span>
                                        <span><i class="icon-comment2 mr-2"></i>5 Comment</span>
                                    </p>
                                </div>
                                <p class="mb-4">{{ object.content }}</p>
                                <p><a href="" class="btn-custom">Read More <span class="ion-ios-arrow-forward"></span></a>
                                </p>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
                {% include 'pagination.html' %}
            </div>
        </section>
    </div>


<div id="ftco-loader" class="show fullscreen">
    <svg class="circular" width="48px" height="48px">
        <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/>
        <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10"
                stroke="#F96D00"/>
    </svg>
</div>
{% endblock %}

templates/posts/index.html
{% extends 'base.html' %}

{% block content %}

        <div id="colorlib-main">
            <section class="ftco-section ftco-no-pt ftco-no-pb">
                <div class="container">
                    <div class="row d-flex">
                        <div class="col-xl-8 py-5 px-md-5">
                            <div class="row pt-md-4">
                                {% for object in object_list %}
                                <div class="col-md-12">
                                    <div class="blog-entry ftco-animate d-md-flex">
                                        <a href="{% url 'posts:single' object.slug %}" class="img img-2"
                                           style="background-image:url({{ object.image.url }})"></a>
                                        <div class="text text-2 pl-md-4">
                                            <h3 class="mb-2"><a href="{% url 'posts:single' object.slug %}">{{ object.title }}</a></h3>
                                            <div class="meta-wrap">
                                                <p class="meta">
                                                    <span><i class="icon-calendar mr-2"></i>{{ object.created_at|date:'M d, Y' }}</span>
                                                    <span><a href="/?cates={{ object.category }}"><i class="icon-folder-o mr-2"></i>{{ object.category }}</a></span>
                                                    <span><i class="icon-comment2 mr-2"></i>{{ object.comment_set.count }} Comment</span>
                                                </p>
                                            </div>
                                            <p class="mb-4">{{ object.content }}</p>
                                            <p><a href="{% url 'posts:home'%}" class="btn-custom">Read More <span
                                                    class="ion-ios-arrow-forward"></span></a></p>
                                            <div class="tag-widget post-tag-container mb-5 mt-5">
                                                <div class="tagcloud">
                                                    {% for tag in object.tags.all %}
                                                        <a href="/?tag={{ tag.tag }}" class="tag-cloud-link">{{ tag.tag }}</a>
                                                    {% endfor %}
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                {% endfor %}
                            </div>

                            {% include 'pagination.html' %}
                        </div>
                        <div class="col-xl-4 sidebar ftco-animate bg-light pt-5">
                            {% include 'rside.html' with categories=categories tag=tags%} 
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>

    <div id="ftco-loader" class="show fullscreen">
        <svg class="circular" width="48px" height="48px">
            <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/>
            <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10"
                    stroke="#F96D00"/>
        </svg>


{% endblock %}

templates/posts/travel.html
{% extends 'base.html' %}
{% block content %}
    <div id="colorlib-main">
        <section class="ftco-section ftco-no-pt ftco-no-pb">
            <div class="container">
                <div class="row d-flex">
                    <div class="col-xl-8 px-md-5 py-5">
                        <div class="row pt-md-4">
                            {% for object in object_list %}
                            <div class="col-md-12">
                                <div class="blog-entry-2 ftco-animate">
                                    <a href="{% url 'posts:single' object.slug %}" class="img"
                                       style="background-image:url({{ object.image.url }})"></a>
                                    <div class="text pt-4">
                                        <h3 class="mb-4"><a href="{% url 'posts:single' object.slug %}">{{ object.title }}</a></h3>
                                        <p class="mb-4">{{ object.written }}</p>
                                        <div class="author mb-4 d-flex align-items-center">
                                            <a href="#" class="img"
                                               style="background-image:url({{ object.written_by.url }})"></a>
                                            <div class="ml-3 info">
                                                <span>Written by</span>
                                                <h3><a href="#">{{ object.name }}</a>, <span>{{ object.created_at|date:'M d, Y ' }}</span></h3>
                                            </div>
                                        </div>
                                        <div class="meta-wrap d-md-flex align-items-center">
                                            <div class="half order-md-last text-md-right">
                                                <p class="meta">
                                                    <span><i class="icon-heart"></i>3</span>
                                                    <span><i class="icon-eye"></i>100</span>
                                                    <span><i class="icon-comment"></i>5</span>
                                                </p>
                                            </div>
                                            <div class="half">
                                                <p><a href="#" class="btn btn-primary p-3 px-xl-4 py-xl-3">Continue
                                                    Reading</a></p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>

                        {% include 'pagination.html' %}
                    </div>
                    <div class="col-xl-4 sidebar ftco-animate bg-light pt-5">
                        {% include 'rside.html' with categories=categories %}
                    </div>
                </div>
            </div>
        </section>
    </div>
    </div>

    <div id="ftco-loader" class="show fullscreen">
        <svg class="circular" width="48px" height="48px">
            <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/>
            <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10"
                    stroke="#F96D00"/>
        </svg>
{% endblock %}

templates/rside.html
{% load static %}
<div class="sidebar-box pt-md-4">
                            <form action="/fashion/"  class="search-form">
                                <div class="form-group">
                                    <span class="icon icon-search"></span>
                                    <input type="text" name='query' class="form-control" placeholder="Type a keyword and hit enter">
                                </div>
                            </form>
                        </div>
                        <div class="sidebar-box ftco-animate">
                            <h3 class="sidebar-heading">Categories</h3>
                            <ul class="categories">
                                {% for category in categories %}
                                <li><a href="/?cates={{ category }}">{{ category }}<span>{{ category.post_set.count }}</span></a></li>
                                {% endfor %}
                            </ul>
                        </div>
                        <div class="sidebar-box ftco-animate">
                            <h3 class="sidebar-heading">Popular Articles</h3>
                            {% for last_2_article in last_2_articles  %}
                            <div class="block-21 mb-4 d-flex">
                                <a class="blog-img mr-4"
                                   style="background-image:url({{ last_2_article.image.url }})"></a>
                                <div class="text">      
                                    <h3 class="heading"><a href="{% url 'posts:single' last_2_article.slug %}">{{ last_2_article.title }}</a>
                                    </h3>
                                    <div class="meta">
                                        <div><a href="#"><span class="icon-calendar"></span>{{ last_2_article.created_at|date:'M d, Y' }}</a></div>
                                        <div><a href="#"><span class="icon-person"></span>{{ last_2_article.name }}</a></div>
                                        <div><a href="#"><span class="icon-chat"></span>{{ last_2_article.count }}</a></div>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}    
                        </div>
                        <div class="sidebar-box ftco-animate">
                            <h3 class="sidebar-heading">Tag Cloud</h3>
                            <ul class="tagcloud">
                                {% for tag in tags %}
                                <a href="/?tag={{ tag }}" class="tag-cloud-link">{{ tag }}</a>
                                {% endfor %}
                            </ul>
                        </div>
                        <div class="sidebar-box subs-wrap img"
                             style="background-image:url({% static 'images/xbg_1.jpg.pagespeed.ic.yyDakF8d8Y.jpg' %})">
                            <div class="overlay"></div>
                            <h3 class="mb-4 sidebar-heading">Newsletter</h3>
                            <p class="mb-4">Far far away, behind the word mountains, far from the countries Vokalia</p>
                            <form method='get' class="colorlib-subscribe-form" >
                                {% csrf_token %}
                                <div class="form-group d-flex">
                                    <div class="icon"><span class="icon-paper-plane"></span></div>
                                    <input type="email" name=email id="submit" class="form-control" placeholder="Subscribe">
                                </div>
                            </form>
                        </div>
                        <div class="sidebar-box ftco-animate">
                            <h3 class="sidebar-heading">Archives</h3>
                            <ul class="categories">
                                {% for object in object_list %}
                                <li><a href="/?object={{ object }}">{{ object.created_at|date:'M Y' }} <span>(10)</span></a></li>
                                {% endfor %}
                            </ul>
                        </div>
                        <div class="sidebar-box ftco-animate">
                            <h3 class="sidebar-heading">Paragraph</h3>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus itaque, autem
                                necessitatibus voluptate quod mollitia delectus aut.</p>
                        </div>

templates/sidebar.html
{% load static %}
        <aside id="colorlib-aside" role="complementary" class="js-fullheight">
            <nav id="colorlib-main-menu" role="navigation">
                <ul>
                    <li><a href="{% url 'posts:home' %}">Home</a></li>
                    <li><a href="{% url 'posts:fashion' %}">Fashion</a></li>
                    <li><a href="{% url 'posts:travel' %}">Travel</a></li>
                    <li><a href="{% url 'posts:about' %}">About</a></li>
                    <li><a href="/contact/">Contact</a></li>
                </ul>
            </nav>
            <div class="colorlib-footer">
                <h1 id="colorlib-logo" class="mb-4"><a href="./"
                                                       style="background-image:url({% static 'images/xbg_1.jpg.pagespeed.ic.yyDakF8d8Y.jpg' %})">Bexzod
                    <span>More</span></a></h1>
                <div class="mb-4">
                    <h3>Subscribe for newsletter</h3>
                    <form method='get' class="colorlib-subscribe-form" >
                        {% csrf_token %}
                        <div class="form-group d-flex">
                            <div class="icon"><span class="icon-paper-plane"></span></div>
                            <input type="email" name=email id="submit" class="form-control" placeholder="Enter Email Address">
                        </div>
                    </form>
                </div>
                <p class="pfooter">
                    Copyright &copy;<script>document.write(new Date().getFullYear());</script>
                    All rights reserved | This template is made with <i class="icon-heart" aria-hidden="true"></i> by <a
                        href="https://colorlib.com/" target="_blank">Colorlib</a>
                </p>
            </div>
        </aside>